language: java
jdk:
  - openjdk17

# Configura las fases del trabajo en Travis CI
jobs:
  include:
    - stage: security
      name: "Build Backend"
      script:
        - cd security
        - mvn install:install-file -Dfile=mvn -DgroupId=org.apache.maven -DartifactId=maven -Dversion=4.0 -Dpackaging=jar
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


    - stage: angular/supermercado
      name: "Build Frontend"
      language: node_js
      node_js:
        - "15.2.0"
      before_script:
        - cd angular/supermercado
        - npm install -g @angular/cli
      script:
        - npm install
        - ng build --prod

# Notifica por correo electrónico en caso de fallos
notifications:
  email:
    recipients:
      - alejoalzate1@gmail.com
    on_success: always
    on_failure: always
