version: '3.9'

networks:
  networks_supermercado:
    driver: bridge

services:
  angular_app:
    networks:
      - networks_supermercado
    container_name: angular_app
    image: appsuperangular:1.0.0
    build: ./angular/supermercado/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    networks:
      - networks_supermercado
    container_name: java_app
    image: appsuper:2.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/supermercadolacosta
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root123
    depends_on:
      - java_db
  java_db:
    networks:
      - networks_supermercado
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: supermercadolacosta
