version: '3.9'

services:
  java_app:
    container_name: java_app
    image: appsuper:2.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/supermercadolacosta
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root123
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: supermercadolacosta
